### ISSUE TITLE
Fetch artifact configuration

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/docker-registry-artifact-plugin#10]
There is a use-case for not pulling down the docker image onto the gocd agent at the time of doing a fetch. Instead, the fetch configuration can specify an easy way to get the image information that can be passed along to the next tasks. For example, if I want to use a newer docker image built by an upstream in a helm chart, I don't need the image to be present on the gocd agent, but I need to be able to pass the image information easily. Today, I have to fetch the <plugin-id>.json file from the gocd server, parse the information in every task that I need the image information in.

**Comment by alexfrancavilla** [comment]
This issue is now open for a while and I'm looking forward for a better solution than the .json workaround (which my team is using as well). Is there any rough time time scale for when this might happen?

Would you otherwise welcome contributions in that direction for a potential pull request?

**Comment by arvindsv** [comment]
@alexfrancavilla As a part of #5508 which was merged recently, the plugin provides environment variables that can be used. There should be no reason to parse the JSON any more.

Do you mean the ability to pull that information, etc. without pulling the image? If it's just a matter of adding a checkbox which says "Don't pull the image", I think that should be ok and would probably be welcomed as a pull request (with a default of false). Unless @varshavaradarajan has any concerns.

**Comment by varshavaradarajan** [comment]
> Unless @varshavaradarajan has any concerns

Just documentation. :) https://plugin-api.gocd.org/current/artifacts doesn't mention anything about the environment variables. https://github.com/gocd/gocd/pull/5188  got merged in 18.11.

**Comment by arvindsv** [comment]
@varshavaradarajan It does! Here: https://plugin-api.gocd.org/current/artifacts/#fetch-artifact

Maybe it needs to be more obvious?

**Comment by arvindsv** [comment]
> I'll see if I can take some time over the holidays to prepare such a pull request - might take a little bit though since I'm unfamiliar with the codebase and Java in specific.

@alexfrancavilla That would be nice! When you get to it (or a couple of days before starting on it), let me know and I'll give you some ideas/suggestions. It should be a small change.

**Comment by alexfrancavilla** [comment]
> @alexfrancavilla That would be nice! When you get to it (or a couple of days before starting on it), let me know and I'll give you some ideas/suggestions. It should be a small change.

Hi @arvindsv! I'd dig into this in the next days, any input is greatly appreciated :)

**Comment by arvindsv** [comment]
@alexfrancavilla I'll take a look at your changeset soon. I just wanted to give you some general suggestions about how to set yourself up for plugin development. If not for you, for others who try it. :)

Usually, the first thing I do is to get a local setup of the plugin working:

1. Download a *zip* of a GoCD server, from https://www.gocd.org/download/#zip (it's the easiet to work with, and throw away when done).

2. Start it using this command-line:

    ```
    GO_SERVER_SYSTEM_PROPERTIES="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -DpluginLocationMonitor.sleepTimeInSecs=1" ./server.sh
    ```

This puts it into a development mode when the plugin location is checked every second for updates. This is not suitable for production use. It also starts it in debug mode, so that a debugger can be attached.

3. Once the server is up (or just before), copy the plugin to `plugins/external` and make sure it works. Set up your test pipeline, etc.

4. Once you have this setup, you can now make changes to your plugin and then copy it over to the directory. I usually do something like:

    ```bash
    ./gradlew assemble && /bin/cp -f build/libs/my-plugin-1.0.0.jar /path/to/zip/go-server-18.11.0/plugins/external/
    ```

That way, every good local "build" is updated and can be tried on the GoCD server, _without restarting it_. Helps the feedback loop a lot.

Occasionally, the server might not reload the plugin properly, etc. Rarely. Only if that happens will you need to restart it.

**Comment by arvindsv** [comment]
> Also I feel like I'm hijacking this issue a bit for a different purpose, should we shift this discussion somewhere else?

A little. :) It's ok, but if you open a PR with your changeset (even though it is not working), we can have a conversation there as well.

**Comment by arvindsv** [comment]
@alexfrancavilla I think you're using an older GoCD server with a newer plugin. The extension version was updated to 2.0 as a [part of the PR](https://github.com/gocd/docker-registry-artifact-plugin/pull/22/files#diff-934f72681e6623f3358d55b794cc0e57R28) I mentioned earlier.

In your case, I think your GoCD server doesn't support it yet, which is why it is complaining about a mismatch in the version. If you used an older plugin with a newer version of the GoCD server, it would work (without that functionality).

So, if you follow step 1 above, and get the latest GoCD server, it should work.

**Comment by arvindsv** [comment]
Your change _look_ alright at first glance. I'll take a deeper look once you open the PR and confirm it works (or need help).

**Comment by alexfrancavilla** [comment]
@arvindsv Thank you for your summary - that was indeed way easier to test the plugin continuously. You were also right with the Go Server version, I didn't notice that I was working with 18.10 (my Helm repo in my minikube dev environment was outdated).

I have polished the changeset, added a unit test and can confirm that it works on my dev environment. Thanks again for your quick and helpful responses, you guys rock!
