### ISSUE TITLE
Support for AWS ECR and GCR container registries too

### ISSUE THREAD

**Issue by rajiesh** [gocd/docker-registry-artifact-plugin#9]
Currently docker registry artifact plugin supports only basic authentication which works well with docker hub and hosted docker registries. Would be good to support Container registries provided by AWS(Elastic container registry) and GCP(Google Container Registry). Authentication methods differ for each of these registries,

https://cloud.google.com/container-registry/docs/advanced-authentication
https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html#registry_auth

cc @varshavaradarajan @akshaydewan @arvindsv

**Comment by ajbarry** [comment]
I just wanted to point out that GCP/GCR does in fact work using the [JSON key file](https://cloud.google.com/container-registry/docs/advanced-authentication#json_key_file) authentication approach described in the documentation linked by @rajiesh 

Here is an example of what my configuration looks like:
![image](https://user-images.githubusercontent.com/359188/46424092-077d4880-c6ed-11e8-8ee9-1fb589c7facd.png)

I've added a Custom Command Task after the build to tag the image appropriately:
`docker tag my-build-image:my-build-tag gcr.io/gocd-example/my-published-image:my-published-tag`
_(different build/publish names are not required)_

Then my build artifact would look like:
![image](https://user-images.githubusercontent.com/359188/46424894-3a284080-c6ef-11e8-9f60-4b96e11edc96.png)

Hope this helps those also wondering if they need to wait for support built into the plugin.

**Comment by itsavvy-ankur** [comment]
I have tried doing something similar but getting a "unauthorized: incorrect username or password"
The service account key file used I have tried it on other ci/cd tool to authorize against GCR , so it works.

Did you have to extract any bits from the service account key to add it as a password ? Or convert the json to a single line ?

It would be nice to have this feature implemented.

**Comment by varshavaradarajan** [comment]
@rajiesh, @sheroy, @arvindsv  - this plugin sort of works with ECR. 
- Executing `aws ecr get-login --no-include-email --region us-east-2` in your terminal gives the docker login command which contains the registry url, username and password. Do not execute the login command. Its not necessary. The password is a token generated by aws that is valid for 12 hours. 
- From the above output, copy the registry url, username and password and set the artifact store fields.
- Configure an external artifact to publish. Provide the image name and tag.
- Run the job to build the docker image and tag it so that it can be pushed to ECR. The image repository must exist in ECR for the push to work. Otherwise, the job fails with `name unknown: The repository with name 'non-existent' does not exist in the registry with id '...'`

I don't think AWS provides any option for long lived tokens to use with CI/CD tools. Apparently, GCR does (haven't verified). Since the token is valid only for 12 hours, may be we can provide an option in the artifact store settings so that `aws ecr get-login` can be executed prior to doing a docker login. Unless one of you know another way to authenticate with ECR.  This means that an aws client must also be provided in the plugin. I think that supporting ECR should be part of this plugin itself as one doesn't have to install multiple plugins to push to different registries. What do you think?

**Comment by varshavaradarajan** [comment]
This can be closed now.

**Comment by bdpiparva** [comment]
Experimental release for the same is available [here](https://github.com/gocd/docker-registry-artifact-plugin/releases/tag/v1.0.1-84-exp).

**Comment by bdpiparva** [comment]
@varshavaradarajan - Stable [release-v1.0.1-92](https://github.com/gocd/docker-registry-artifact-plugin/releases/tag/v1.0.1-92) with ECR support is available now.
